Ads:
  description: Programma satur reklāmu
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: Šai lietotnei ir vājš drošības paraksts
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: Šī lietotne satur zināmu drošības ievainojamību
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Avota kods vairs nav pieejams, nav iespējami atjauninājumi.
NonFreeAdd:
  description: Šī lietotne atbalsta ne-brīvus paplašinājumus
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: Šī lietotne satur ne-brīvas sastāvdaļas
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: Šī lietotne ir atkarīga no citām ne-brīvām lietotnēm
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: Šī lietotne atbalsta ne-brīvus tīklus
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: Šī programma seko jūsu aktivitātēm un ziņo par tām
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: Augšējā avota kods nav pilnībā brīvs
  icon: ic_antifeature_upstreamnonfree.png
