Ads:
  description: Programma satur reklāmu
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Šai lietotnei ir vājš drošības paraksts
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Šī lietotne satur zināmu drošības ievainojamību
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Avota kods vairs nav pieejams, nav iespējami atjauninājumi.
NonFreeAdd:
  description: Šī lietotne atbalsta ne-brīvus paplašinājumus
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Šī lietotne satur ne-brīvas sastāvdaļas
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Šī lietotne ir atkarīga no citām ne-brīvām lietotnēm
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Šī lietotne atbalsta ne-brīvus tīklus
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Šī programma seko jūsu aktivitātēm un ziņo par tām
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: Augšējā avota kods nav pilnībā brīvs
  icon: ic_antifeature_upstreamnonfree.xml
