Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Savienojamība
Development:
  name: Izstrādāšana
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spēles
Graphics:
  name: Grafika
Internet:
  name: Internets
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Nauda
Multimedia:
  name: Multivides
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigācija
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Tālrunis & īsziņa
Reading:
  name: Lasījumam
Science & Education:
  name: Zinātne un Izglītība
Security:
  name: Drošība
Sports & Health:
  name: Sports un veselība
System:
  name: Sistēmas
Theming:
  name: Motīvi
Time:
  name: Laiks
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Rakstīšana
