Connectivity:
  name: Connetividade
Development:
  name: Isvilupu
Games:
  name: Giogos
Graphics:
  name: Gràfica
Internet:
  name: Ìnternet
Money:
  name: Dinare
Multimedia:
  name: Multimèdia
Navigation:
  name: Nàvigu
Phone & SMS:
  name: Telèfono & SMS
Reading:
  name: Letura
Science & Education:
  name: Iscièntzia e educatzione
Security:
  name: Seguràntzia
Sports & Health:
  name: Isport e Salude
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempus
Writing:
  name: Iscritura
App Store & Updater:
  name: Butega de aplicatziones e atualizadore
Bookmark:
  name: Sinnalibru
Browser:
  name: Navigadore
Calculator:
  name: Carculadora
Calendar & Agenda:
  name: Calendàriu e agenda
Cloud Storage & File Sync:
  name: Archiviatzione in sa nue e sincronizada de documentos
Draw:
  name: Disinnu
Ebook Reader:
  name: Leghidore de libros eletrònicos
Email:
  name: Posta eletrònica
File Encryption & Vault:
  name: Tzifradura de documentos e cassaforte
File Transfer:
  name: Tràmuda de documentos
Finance Manager:
  name: Gestore de finàntzias
Gallery:
  name: Galleria
Icon Pack:
  name: Pachete de iconas
Keyboard & IME:
  name: Tecladu e mètodos de intrada (IME)
Local Media Player:
  name: Leghidore multimediale locale
Messaging:
  name: Messagìstica
News:
  name: Novas
Note:
  name: Nota
Online Media Player:
  name: Leghidore multimediale in lìnia
Password & 2FA:
  name: Crae de intrada e autenticatzione a duos fatores
Podcast:
  name: Podcast
Public Transport Map & Timetable:
  name: Oràrios e mapas de sos trasportos pùblicos
Recipe Manager:
  name: Manigiadore de retzetas
Shopping List:
  name: Lista de còmporas
Social Network:
  name: Retes sotziales
Task:
  name: Faina
Text Editor:
  name: Editore de testu
Translation & Dictionary:
  name: Tradutzione e ditzionàriu
Unit Convertor:
  name: Cunvertidore de unidades
Voice & Video Chat:
  name: Tzarrada de boghe e vìdeu
VPN & Proxy:
  name: VPN e serbidores intermediàrios
Wallet:
  name: Taschinu
Wallpaper:
  name: Isfundu
Weather:
  name: Mèteu
Workout:
  name: Allenamentu
DNS & Hosts:
  name: DNS e retzidores (hosts)
Launcher:
  name: Aviadores de aplicatziones
Pass Wallet:
  name: Portafòlliu de cartas e billetes
