Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Connetividade
Development:
  name: Isvilupu
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Giogos
Graphics:
  name: Gràfica
Internet:
  name: Ìnternet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Dinare
Multimedia:
  name: Multimèdia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Nàvigu
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telèfono & SMS
Reading:
  name: Letura
Science & Education:
  name: Iscièntzia e educatzione
Security:
  name: Seguràntzia
Sports & Health:
  name: Isport e Salude
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempus
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Iscritura
