Ads:
  description: Esta aplicación tiene publicidad
  icon: ic_antifeature_ads.xml
  name: Anuncios
DisabledAlgorithm:
  description: Esta aplicación tiene una firma de seguridad débil
  icon: ic_antifeature_disabledalgorithm.xml
  name: Firmado usando un algoritmo no seguro
KnownVuln:
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
  icon: ic_antifeature_knownvuln.xml
  name: Vulnerabilidad conocida
NSFW:
  description: Esta app contiene contenido que no debería ser publicitado o visible
    en cualquier lugar
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: El código fuente ya no está disponible, no se puede actualizar.
NonFreeAdd:
  description: Esta aplicación promueve complementos no libres
  icon: ic_antifeature_nonfreeadd.xml
  name: Complementos no libres
NonFreeAssets:
  description: Esta aplicación contiene recursos que no son libres
  icon: ic_antifeature_nonfreeassets.xml
  name: Activos no libres
NonFreeDep:
  description: Esta aplicación depende de otras no libres
  icon: ic_antifeature_nonfreedep.xml
  name: Dependencias no libres
NonFreeNet:
  description: Esta aplicación promueve servicios de red no libres
  icon: ic_antifeature_nonfreenet.xml
  name: Servicios de red no libres
Tracking:
  description: Esta aplicación rastrea e informa de su actividad
  icon: ic_antifeature_tracking.xml
  name: Rastreo
UpstreamNonFree:
  description: El código fuente original no es totalmente libre
  icon: ic_antifeature_upstreamnonfree.xml
  name: Original no libre
