Ads:
  description: Appen inneheld reklame
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Appen har ein svak tryggleikssignatur
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Appen inneheld eit kjent tryggleikshòl
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Kjeldekoden er ikkje lenger tilgjengeleg, så det er ikkje mogleg med oppdatering.
NonFreeAdd:
  description: Appen marknadsfører ufrie tillegg
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Appen inneheld ufrie ressursar
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Appen er avhengig av andre ufrie appar
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Appen marknadsfører ufrie nett-tenester
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Denne appen sporar og rapporterer aktiviteten din
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: Kjeldekoden til oppstraums­appen er ikkje heilt fri
  icon: ic_antifeature_upstreamnonfree.xml
