Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Samband
Development:
  name: Utvikling
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spel
Graphics:
  name: Bilete
Internet:
  name: Internett
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Økonomi
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigasjon
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon og SMS
Reading:
  name: Lesing
Science & Education:
  name: Vitskap og utdanning
Security:
  name: Tryggleik
Sports & Health:
  name: Idrett og helse
System:
  name: System
Theming:
  name: Tema
Time:
  name: Tid
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skriving
