Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Connectioun
Development:
  name: Entwécklung
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spiller
Graphics:
  name: Grafik
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Suen
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigatioun
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Liesen
Science & Education:
  name: Wëssenschaft & Bildung
Security:
  name: Sécherheet
Sports & Health:
  name: Sport & Gesondheet
System:
  name: System
Time:
  name: Zäit
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Schreiwen
