Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Conectivitate
Development:
  name: Dezvoltare programe
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Jocuri
Graphics:
  name: Grafică
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Finanțe
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigație
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Citit
Science & Education:
  name: Știință & educație
Security:
  name: Securitate
Sports & Health:
  name: Sport & sănătate
System:
  name: Sistem
Theming:
  name: Teme
Time:
  name: Timp
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Scris
