Connectivity:
  name: Conectivitate
Development:
  name: Dezvoltare programe
Games:
  name: Jocuri
Graphics:
  name: Grafică
Internet:
  name: Internet
Money:
  name: Finanțe
Multimedia:
  name: Multimedia
Navigation:
  name: Navigație
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Citit
Science & Education:
  name: Știință & educație
Security:
  name: Securitate
Sports & Health:
  name: Sport & sănătate
System:
  name: Sistem
Theming:
  name: Teme
Time:
  name: Timp
Writing:
  name: Scris
Email:
  name: E-mail
DNS & Hosts:
  name: DNS & Gazde
VPN & Proxy:
  name: VPN & Proxy
File Encryption & Vault:
  name: Criptare fișiere și seif
File Transfer:
  name: Transfer fișiere
Messaging:
  name: Mesagerie
Password & 2FA:
  name: Parole & 2FA
Social Network:
  name: Rețea socială
App Store & Updater:
  name: Magazin aplicații & Actualizări
Browser:
  name: Navigator web
Local Media Player:
  name: Vizualizator media local
News:
  name: Știri
Online Media Player:
  name: Vizualizator media pe Internet
Podcast:
  name: Podcast
Weather:
  name: Meteo
Keyboard & IME:
  name: Tastatură & IME
