Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Conectividade
Development:
  name: Desenvolvemento
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Xogos
Graphics:
  name: Gráficas
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Cartos
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigación
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Teléfono móbil e SMS
Reading:
  name: Lectura
Science & Education:
  name: Ciencia e educación
Security:
  name: Seguranza
Sports & Health:
  name: Deportes e saúde
System:
  name: Sistema
Theming:
  name: Aparencia
Time:
  name: Tempo
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Escrita
