Ads:
  description: Esta aplicación tiene publicidad
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Esta aplicación tiene una firma de seguridad débil
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: El código fuente ya no está disponible, ninguna actualización posible.
NonFreeAdd:
  description: Esta aplicación promueve complementos no libres
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Esta aplicación contiene recursos no libres
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Esta aplicación depende de otras aplicaciones no libres
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Esta aplicación promueve servicios no libres
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Esta aplicación rastrea e informa de tu actividad
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: El codigo fuente de subida no es completamente libre
  icon: ic_antifeature_upstreamnonfree.xml
