Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Comas-ceangail
Development:
  name: Leasachadh
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Geamannan
Graphics:
  name: Grafaigeachd
Internet:
  name: Eadar-lìon
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Airgead
Multimedia:
  name: Meadhanan
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Seòladaireachd
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Fòn ⁊ SMS
Reading:
  name: Leughadh
Science & Education:
  name: Saidheans ⁊ foghlam
Security:
  name: Tèarainteachd
Sports & Health:
  name: Spòrs ⁊ slàinte
System:
  name: An siostam
Theming:
  name: Ùrlaran
Time:
  name: Àm
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Sgrìobhadh
