Ads:
  description: Овај програм садржи огласе
  icon: ic_antifeature_ads.png
  name: Додаци
DisabledAlgorithm:
  description: Овај програм има слаб безбедносни потпис
  icon: ic_antifeature_disabledalgorithm.png
  name: Потписано несигурним алгоритмом
KnownVuln:
  description: Овај програм садржи познату безбедносну рањивост
  icon: ic_antifeature_knownvuln.png
  name: Позната рањивост
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Изворни код није више доступан, нема доступних надградњи.
NonFreeAdd:
  description: Овај програм предлаже неслободне додатке
  icon: ic_antifeature_nonfreeadd.png
  name: Неслободни додаци
NonFreeAssets:
  description: Овај програм поседује неслободан садржај
  icon: ic_antifeature_nonfreeassets.png
  name: Неслободна припадност
NonFreeDep:
  description: Овај програм зависи од неслободних програма
  icon: ic_antifeature_nonfreedep.png
  name: Неслободне зависности
NonFreeNet:
  description: Овај програм предлаже неслободне мрежне услуге
  icon: ic_antifeature_nonfreenet.png
  name: Неслободне мрежне услуге
Tracking:
  description: Програм прати и пријављује Ваша дејства
  icon: ic_antifeature_tracking.png
  name: Праћење
UpstreamNonFree:
  description: Изворни кôд није у потпуности слободан
  icon: ic_antifeature_upstreamnonfree.png
  name: Узводна неслободност
