Connectivity:
  name: Aftësi lidhjeje
  icon: category_connectivity.png
Development:
  name: Zhvillim
  icon: category_development.png
Games:
  name: Lojëra
  icon: category_games.png
Graphics:
  name: Grafika
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Para
  icon: category_money.png
Multimedia:
  name: Multimedia
Navigation:
  name: Lëvizje
  icon: category_navigation.png
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Lexim
  icon: category_reading.png
Science & Education:
  name: Shkencë & Arsim
  icon: category_science_education.png
Security:
  name: Siguri
  icon: category_security.png
Sports & Health:
  name: Sporte & Shëndet
System:
  name: Sistem
  icon: category_system.png
Theming:
  name: Ndryshim teme grafike
  icon: category_theming.png
Time:
  name: Kohë
Writing:
  name: Shkrim
  icon: category_writing.png
