Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Kết nối
Development:
  name: Lập trình
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Trò chơi
Graphics:
  name: Đồ hoạ
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Tài chính
Multimedia:
  name: Đa phương tiện
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Điều hướng
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Đàm thoại & nhắn tin
Reading:
  name: Đọc
Science & Education:
  name: Khoa học & giáo dục
Security:
  name: Bảo mật
Sports & Health:
  name: Thể thao & sức khoẻ
System:
  name: Hệ thống
Theming:
  name: Giao diện
Time:
  name: Thời gian
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Soạn thảo
