Connectivity:
  name: Conectividade
Development:
  name: Desenvolvimento
Games:
  name: Jogos
Graphics:
  name: Gráficos
Internet:
  name: Internet
Money:
  name: Dinheiro
Multimedia:
  name: Multimídia
Navigation:
  name: Navegação
Phone & SMS:
  name: Telefone & SMS
Reading:
  name: Leitura
Science & Education:
  name: Ciência & Educação
Security:
  name: Segurança
Sports & Health:
  name: Esportes & Saúde
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempo
Writing:
  name: Escrita
Email:
  name: E-mail
VPN & Proxy:
  name: VPN e proxy
DNS & Hosts:
  name: DNS e domínios
Messaging:
  name: Mensageiros
Password & 2FA:
  name: Senhas e dois fatores
File Transfer:
  name: Transferência de arquivos
File Encryption & Vault:
  name: Criptografia de arquivos e cofres
Social Network:
  name: Redes sociais
App Store & Updater:
  name: Loja de apps e atualizador
Browser:
  name: Navegador
Keyboard & IME:
  name: Teclado e métodos de entrada
Local Media Player:
  name: Reprodutor de mídia local
News:
  name: Notícias
Online Media Player:
  name: Reprodutor de mídia on-line
Podcast:
  name: Podcast
Weather:
  name: Clima
Calendar & Agenda:
  name: Calendário e agenda
Cloud Storage & File Sync:
  name: Armazenamento na nuvem e sincronização de arquivos
Voice & Video Chat:
  name: Ligação de voz e vídeo
Wallet:
  name: Carteira
