Ads:
  icon: ic_antifeature_ads.xml
Development:
  name: ⵜⵉⴳⵎⵉ
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: ⵓⵔⴰⵔⵏ
Internet:
  name: ⴰⵏⵜⵉⵔⵏⵉⵜ
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: ⴰⵥⵕⴼ
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Reading:
  name: ⵜⵉⵖⵓⵔⵉ
Science & Education:
  name: ⵜⴰⵎⴰⵙⵙⴰⵏⵜ ⴷ ⵓⵙⴳⵎⵉ
Security:
  name: ⵙⵙⵍⴰⵎⵜ
Time:
  name: ⴰⴳⵓⵔ
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: ⵜⵉⵔⵔⴰ
