Connectivity:
  name: Nascacht
Development:
  name: Forbairt
Games:
  name: Cluichí
Graphics:
  name: Grafaicí
Internet:
  name: Idirlíon
Reading:
  name: Léamh
Navigation:
  name: Loingseoireacht
Phone & SMS:
  name: Fón & SMS
Science & Education:
  name: Eolaíocht & Oideachas
Security:
  name: Slándáil
Sports & Health:
  name: Spóirt & Sláinte
System:
  name: Córas
Theming:
  name: Téamaí
Time:
  name: Am
Money:
  name: Airgead
Multimedia:
  name: Ilmheáin
Writing:
  name: Ag scríobh
Email:
  name: Ríomhphost
VPN & Proxy:
  name: VPN & Seachfhreastalaí
DNS & Hosts:
  name: DNS & Óstaigh
App Store & Updater:
  name: App Store & Nuashonraitheoir
Browser:
  name: Brabhsálaí
File Encryption & Vault:
  name: Criptiú Comhad & Cruinneachán
File Transfer:
  name: Aistriú Comhad
Social Network:
  name: Líonra Sóisialta
Local Media Player:
  name: Seinnteoir Meán Áitiúil
Weather:
  name: Aimsir
News:
  name: Nuacht
Online Media Player:
  name: Seinnteoir Meán Ar Líne
Password & 2FA:
  name: Pasfhocal agus 2FA
Podcast:
  name: Podchraoladh
Keyboard & IME:
  name: Méarchlár & IME
Messaging:
  name: Teachtaireachtaí
