Ads:
  description: Hierdie program bevat advertensies
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Hierdie app het \'n swak sekuriteitshandtekening
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Hierdie inligting bevat \'n bekende veiligheidskwesbaarheid
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Die bronkode is nie meer beskikbaar nie, geen opdaterings moontlik nie.
NonFreeAdd:
  description: Hierdie program bevorder nie-vrye toevoegsels
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Hierdie program bevat nie-vrye bates
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Hierdie program is afhanklik van ander nie-vrye programme
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Hierdie program bevorder nie-vrye netwerk dienste
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Hierdie program speur op, en rapporteer jou aktiwiteite
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: Die stroomop bronkode is nie heeltemal vry nie
  icon: ic_antifeature_upstreamnonfree.xml
