Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Konnektiwiteit
Development:
  name: Ontwikkeling
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Speletjies
Graphics:
  name: Grafika
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Geld
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigasie
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefoon & SMS
Reading:
  name: Lees
Science & Education:
  name: Wetenskap en onderwys
Security:
  name: Sekuriteit
Sports & Health:
  name: Sport en gesondheid
System:
  name: Stelsel
Theming:
  name: Thema\'s
Time:
  name: Tyd
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skryf
