Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Ku
Development:
  name: Hormarka
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Geemamka
Graphics:
  name: Farshaxa
Internet:
  name: Khadka
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Lacag
Multimedia:
  name: Lagu
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Dhex
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Taleefanka &
Reading:
  name: Akhriska
Science & Education:
  name: Sayniska & Waxbarashada
Security:
  name: Amniga
Sports & Health:
  name: Ciyaaraha & Caafimaadka
System:
  name: Aalada
Time:
  name: Wakhtiga
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Qorista
