Ads:
  description: This app contains advertising
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: This app has a weak security signature
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: This app contains a known security vulnerability
  icon: ic_antifeature_knownvuln.xml
NSFW:
  description: This app contains content that should not be publicised or visible
    everywhere
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: The source code is no longer available, no updates possible.
NonFreeAdd:
  description: This app promotes non-free add-ons
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: This app contains non-free assets
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: This app depends on other non-free apps
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: This app promotes non-free network services
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: This app tracks and reports your activity
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: The upstream source code is not entirely Free
  icon: ic_antifeature_upstreamnonfree.xml
