Ads:
  description: This app contains advertising
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: This app has a weak security signature
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: This app contains a known security vulnerability
  icon: ic_antifeature_knownvuln.png
NSFW:
  description: This app contains content that should not be publicised or visible
    everywhere
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: The source code is no longer available, no updates possible.
NonFreeAdd:
  description: This app promotes non-free add-ons
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: This app contains non-free assets
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: This app depends on other non-free apps
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: This app promotes non-free network services
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: This app tracks and reports your activity
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: The upstream source code is not entirely Free
  icon: ic_antifeature_upstreamnonfree.png
