Connectivity:
  name: Povezljivost
Development:
  name: Razvijanje
Games:
  name: Igre
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Denar
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Branje
Science & Education:
  name: Znanost & Izobrazba
Security:
  name: Varnost
Sports & Health:
  name: Šport & zdravje
System:
  name: Sistem
Theming:
  name: Izgled
Time:
  name: Čas
Writing:
  name: Pisanje
App Store & Updater:
  name: App trgovina in posodobitve
Bookmark:
  name: Zaznamek
Browser:
  name: Brskalnik
Calculator:
  name: Kalkulator
Calendar & Agenda:
  name: Koledar in urnik
Cloud Storage & File Sync:
  name: Shranjevanje v oblaku in sinhronizacija datotek
DNS & Hosts:
  name: DNS in gostitelji
Draw:
  name: Riši
Ebook Reader:
  name: Bralnik e-knjig
Email:
  name: E-pošta
