Ads:
  description: Tämä sovellus sisältää mainoksia
  icon: ic_antifeature_ads.xml
  name: Mainokset
DisabledAlgorithm:
  description: Tällä sovelluksella on heikko turvallisuusallekirjoitus
  icon: ic_antifeature_disabledalgorithm.xml
  name: Allekirjoitettu turvattomalla algoritmilla
KnownVuln:
  description: Tämä sovellus sisältää tunnetun haavoittuvuuden
  icon: ic_antifeature_knownvuln.xml
  name: Tunnettu haavoittuvuus
NSFW:
  description: Sovelluksessa on sisältöä, jota ei tulisi julkaista tai näyttää kaikkialla
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Lähdekoodi ei ole enää saatavilla, päivityksiä ei voi tehdä.
NonFreeAdd:
  description: Tämä sovellus suosittelee ei-vapaita lisäosia
  icon: ic_antifeature_nonfreeadd.xml
  name: Ei-vapaat lisäosat
NonFreeAssets:
  description: Tämä sovellus sisältää ei-vapaita osia
  icon: ic_antifeature_nonfreeassets.xml
  name: Ei-vapaa sisältö
NonFreeDep:
  description: Tämä sovellus on riippuvainen muista, ei-vapaista sovelluksista
  icon: ic_antifeature_nonfreedep.xml
  name: Ei-vapaat riippuvuudet
NonFreeNet:
  description: Tämä sovellus tukee ei-vapaita verkkopalveluja
  icon: ic_antifeature_nonfreenet.xml
  name: Ei-vapaat verkkopalvelut
Tracking:
  description: Tämä sovellus tarkkailee ja raportoi toimintaasi
  icon: ic_antifeature_tracking.xml
  name: Seuranta
UpstreamNonFree:
  description: Ylätason lähdekoodi ei ole kokonaan vapaata
  icon: ic_antifeature_upstreamnonfree.xml
  name: Upstream ei-vapaa
