Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Yhteydet
Development:
  name: Kehittäminen
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Pelit
Graphics:
  name: Grafiikka
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Raha
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigointi
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Puhelin & SMS
Reading:
  name: Lukeminen
Science & Education:
  name: Tiede & koulutus
Security:
  name: Tietoturva
Sports & Health:
  name: Urheilu & terveys
System:
  name: Järjestelmä
Theming:
  name: Teemat
Time:
  name: Aika
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Kirjoittaminen
