Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Связь
Development:
  name: Разработка
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Игры
Graphics:
  name: Графика
Internet:
  name: Интернет
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Финансы
Multimedia:
  name: Мультимедиа
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Навигация
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Звонки и сообщения
Reading:
  name: Чтение
Science & Education:
  name: Наука и образование
Security:
  name: Безопасность
Sports & Health:
  name: Спорт и здоровье
System:
  name: Системные
Theming:
  name: Оформление
Time:
  name: Часы
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Офис
