Ads:
  description: App ino ine zvakashambadzwa zvemamwe makambani
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  description: App inosesedza zvinowedzerwa paapp ino zvinobhadharwa
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: App ino inenhumbi dzinobhadharwa
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: App ino inotemba nemamwe maapps anobhadharwa
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: App ino inosesedza zvirango zvemasaisai zvinobhadharwa
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: App ino inotevera nekududzira zvauri kuita
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: Nyuko yemurau irikumberi haisi yemahara
  icon: ic_antifeature_upstreamnonfree.xml
