Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Mahakiro
Development:
  name: Tsvitsa
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Mitambo
Graphics:
  name: Magraphics
Internet:
  name: Dandemutande
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Mari
Multimedia:
  name: Midhiya yakasiyana
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Mafambiro
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Nhare neTsamba pfupi
Reading:
  name: Kuverenga
Science & Education:
  name: zveScience neFundo
Security:
  name: Zvekukwdekwera
Sports & Health:
  name: Nhabvu neUtano
System:
  name: Sistemu
Theming:
  name: Kudingindira
Time:
  name: Nguva
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Kunyora
