Ads:
  description: Dizze applikaasje hat advertinsjes
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Dizze applikaasje hat net in sterke feiligens 没ndertekening
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Dizze applikaasje hat in bekend feiligens probleem
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: De boarne koade is net langer beskikber, gjin fernijingen mooglik.
NonFreeAdd:
  description: Dizze applikaasje stimulearret it gebr没k fan net-frije add-ons
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Dizze applikaasje hinget 么f fan oare net-frije applikaasjes
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Dizze applikaasje stimulearret it gebr没k fan net-frije netwurk tsjinsten
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Dizze applikaasje folget en rapportearret jo aktiviteit
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
