Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Ferbiningen
Development:
  name: Ûntwikkeling
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spultsjes
Graphics:
  name: Grafysk
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Jild
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigaasje
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefoan & SMS
Reading:
  name: Lêze
Science & Education:
  name: Wittenskip & Edukaasje
Security:
  name: Befeiliging
Sports & Health:
  name: Sport & Sûnens
System:
  name: Systeem
Time:
  name: Tiid
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skrieuwe
