Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Azday
Development:
  name: asbuɣlu
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: uraren
Graphics:
  name: Tiwwunɣa
Internet:
  name: antirnit
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: aẓeṛf
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Reading:
  name: tiɣuri
Science & Education:
  name: Tamassant d usegmi
System:
  name: Anegraw
Time:
  name: Akud
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Tirra
