Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Sareak
Development:
  name: Garapena
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Jolasak
Graphics:
  name: Grafikoak
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Dirua
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Orientazioa
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefonoa eta SMS
Reading:
  name: Irakurketa
Science & Education:
  name: Zientzia eta hezkuntza
Security:
  name: Segurtasuna
Sports & Health:
  name: Kirola eta osasuna
System:
  name: Sistema
Theming:
  name: Itxura
Time:
  name: Denbora
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Idazketa
