Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Tillslutningsmuligheder
Development:
  name: Udvikling
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spil
Graphics:
  name: Grafik
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Penge
Multimedia:
  name: Multimedier
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigation
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon og SMS
Reading:
  name: Læsning
Science & Education:
  name: Videnskab og uddannelse
Security:
  name: Sikkerhed
Sports & Health:
  name: Sport og sundhed
System:
  name: System
Theming:
  name: Temaer
Time:
  name: Tid
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skrivning
