Connectivity:
  name: 连接
  icon: category_connectivity.png
Development:
  name: 开发
Games:
  name: 游戏
  icon: category_games.png
Graphics:
  name: 图像
  icon: category_graphics.png
Internet:
  name: 网络
Money:
  name: 理财
  icon: category_money.png
Multimedia:
  name: 多媒体
Navigation:
  name: 导航
Phone & SMS:
  name: 通话与短信
Reading:
  name: 阅读
  icon: category_reading.png
Science & Education:
  name: 科学与教育
  icon: category_science_education.png
Security:
  name: 安全
  icon: category_security.png
Sports & Health:
  name: 运动与健康
System:
  name: 系统
  icon: category_system.png
Theming:
  name: 主题
  icon: category_theming.png
Time:
  name: 时间
Writing:
  name: 记录
  icon: category_writing.png
