Ads:
  description: Tiu ĉi aplikaĵo enhavas reklamojn
  icon: ic_antifeature_ads.xml
  name: Reklamoj
DisabledAlgorithm:
  description: Tiu ĉi aplikaĵo posedas malfortan sekurecan subskribon
  icon: ic_antifeature_disabledalgorithm.xml
  name: Subskribita per malsekura algoritmo
KnownVuln:
  description: Tiu ĉi aplikaĵo posedas sekurecan vundeblon
  icon: ic_antifeature_knownvuln.xml
  name: Konata sekureca vundeblo
NSFW:
  description: Tiu ĉi aplikaĵo liveras enhavon, kiu ne estas taŭga por rigardi publike
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: La fontkodo ne estas plu disponebla, neniu ebla ĝisdatigo.
NonFreeAdd:
  description: Tiu ĉi aplikaĵo favoras neliberajn aldonaĵojn
  icon: ic_antifeature_nonfreeadd.xml
  name: Neliberaj aldonaĵoj
NonFreeAssets:
  description: Tiu ĉi aplikaĵo enhavas neliberan enhavon
  icon: ic_antifeature_nonfreeassets.xml
  name: Nelibera enhavo
NonFreeDep:
  description: Tiu ĉi aplikaĵo dependas de aliaj neliberaj aplikaĵoj
  icon: ic_antifeature_nonfreedep.xml
  name: Neliberaj dependecoj
NonFreeNet:
  description: Tiu ĉi aplikaĵo favoras neliberajn retservojn
  icon: ic_antifeature_nonfreenet.xml
  name: Neliberaj retservoj
Tracking:
  description: Tiu ĉi aplikaĵo spuras kaj raportas vian agadon
  icon: ic_antifeature_tracking.xml
  name: Spurado
UpstreamNonFree:
  description: La fontkodo ne estas tute libera
  icon: ic_antifeature_upstreamnonfree.xml
  name: Parte libera fontkodo
