Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Konekteco
Development:
  name: Programado
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Ludoj
Graphics:
  name: Grafiko
Internet:
  name: Interreto
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Mono
Multimedia:
  name: Plurmedioj
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigado
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefono k SMS
Reading:
  name: Legado
Science & Education:
  name: Scienco k edukado
Security:
  name: Sekureco
Sports & Health:
  name: Sporto k sano
System:
  name: Sistemo
Theming:
  name: Etosoj k aspekto
Time:
  name: Tempo
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skribado
