Connectivity:
  name: Konekteco
Development:
  name: Programado
Games:
  name: Ludoj
Graphics:
  name: Grafiko
Internet:
  name: Interreto
Money:
  name: Financoj
Multimedia:
  name: Sono kaj video
Navigation:
  name: Navigado
Phone & SMS:
  name: Telefonado kaj SMS
Reading:
  name: Legado
Science & Education:
  name: Scienco kaj edukado
Security:
  name: Sekureco
Sports & Health:
  name: Sporto kaj sano
System:
  name: Operaciumaj iloj
Theming:
  name: Haŭtoj (etosoj)
Time:
  name: Tempo
Writing:
  name: Skribado
Email:
  name: Retpoŝto
VPN & Proxy:
  name: VPN kaj retperiloj
DNS & Hosts:
  name: DNS kaj retgastigo
Social Network:
  name: Sociaj komunikiloj
App Store & Updater:
  name: Deponejoj kaj ĝisdatigiloj de aplikaĵoj
Browser:
  name: Retfoliumiloj
File Encryption & Vault:
  name: Dosiera ĉifrado
File Transfer:
  name: Dosiera kunhavigo
Keyboard & IME:
  name: Klavaroj
Local Media Player:
  name: Ludiloj de lokaj aŭdvidaĵoj
Messaging:
  name: Komunikiloj
News:
  name: Novaĵ-legiloj
Online Media Player:
  name: Ludiloj de foraj aŭdvidaĵoj
Password & 2FA:
  name: Pasvort-administriloj kaj dupaŝaj aŭtentigiloj
Podcast:
  name: Ludiloj de aboneblaj sondosieroj (podkastoj)
Weather:
  name: Veterprognozo
Calendar & Agenda:
  name: Kalendaroj kaj planiloj
Cloud Storage & File Sync:
  name: Nuba konservado kaj dosiera samtempigo
Voice & Video Chat:
  name: Sonaj/videaj komunikiloj
Wallet:
  name: Monujoj
