Ads:
  description: Mae\'r ap hwn yn cynnwys hysbysebion
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Mae gan yr ap hwn llofnod diogelwch wan
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Mae\'r ap hwn yn cynnwys gwendid diogelwch hysbys
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Dyw\'r cod gwreiddiol ddim bellach ar gael a dim diweddariadau\'n bosib.
NonFreeAdd:
  description: Mae\'r ap hwn yn hyrwyddo ychwanegiadau sy\'n codi tâl
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Mae\'r ap hwn yn cynnwys asedau sydd am ddim
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Mae\'r ap hwn yn dibynnu ar apiau eraill sy\'n codi tâl
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Mae\'r ap hwn yn hyrwyddo gwasanaethau rhwydwaith sy\'n codi tâl
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Mae\'r ap hwn yn tracio ac adrodd dy weithgaredd
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: Dyw\'r cod uwchffrydio ddim yn gwbl am ddim
  icon: ic_antifeature_upstreamnonfree.xml
