Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Cysylltedd
Development:
  name: Datblygiad
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Gemau
Graphics:
  name: Graffigau
Internet:
  name: Rhyngrwyd
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Arian
Multimedia:
  name: Aml-gyfrwng
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Llywio
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Ffôn ac SMS
Reading:
  name: Darllen
Science & Education:
  name: Gwyddoniaeth ac Addysg
Security:
  name: Diogelwch
Sports & Health:
  name: Chwaraeon a Iechyd
System:
  name: System
Theming:
  name: Themáu
Time:
  name: Amser
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Ysgrifennu
