Connectivity:
  name: Konektivitas
  icon: category_connectivity.png
Development:
  name: Pengembangan
  icon: category_development.png
Games:
  name: Permainan
  icon: category_games.png
Graphics:
  name: Grafis
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Finansial
  icon: category_money.png
Multimedia:
  name: Multimedia
Navigation:
  name: Navigasi
Phone & SMS:
  name: Telepon & SMS
Reading:
  name: Membaca
  icon: category_reading.png
Science & Education:
  name: Sains & Edukasi
  icon: category_science_education.png
Security:
  name: Keamanan
  icon: category_security.png
Sports & Health:
  name: Olahraga & Kesehatan
System:
  name: Sistem
  icon: category_system.png
Theming:
  name: Personalisasi
  icon: category_theming.png
Time:
  name: Waktu
Writing:
  name: Menulis
  icon: category_writing.png
