Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Konektivitas
Development:
  name: Pengembangan
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Permainan
Graphics:
  name: Grafis
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Finansial
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigasi
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telepon & SMS
Reading:
  name: Membaca
Science & Education:
  name: Sains & Edukasi
Security:
  name: Keamanan
Sports & Health:
  name: Olahraga & Kesehatan
System:
  name: Sistem
Theming:
  name: Personalisasi
Time:
  name: Waktu
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Menulis
