Connectivity:
  name: Konektivitas
Development:
  name: Pengembangan
Games:
  name: Permainan
Graphics:
  name: Grafis
Internet:
  name: Internet
Money:
  name: Finansial
Multimedia:
  name: Multimedia
Navigation:
  name: Navigasi
Phone & SMS:
  name: Telepon & SMS
Reading:
  name: Membaca
Science & Education:
  name: Sains & Edukasi
Security:
  name: Keamanan
Sports & Health:
  name: Olahraga & Kesehatan
System:
  name: Sistem
Theming:
  name: Personalisasi
Time:
  name: Waktu
Writing:
  name: Menulis
DNS & Hosts:
  name: DNS & Hos
Email:
  name: Surel
App Store & Updater:
  name: Toko Aplikasi & Aplikasi Pembaruan
Browser:
  name: Peramban
File Encryption & Vault:
  name: Enkripsi Berkas & Brankas
File Transfer:
  name: Transfer Berkas
Messaging:
  name: Perpesanan
News:
  name: Berita
Password & 2FA:
  name: Kata Sandi & 2FA
Podcast:
  name: Siniar
VPN & Proxy:
  name: VPN & Proksi
Weather:
  name: Cuaca
Local Media Player:
  name: Pemutar Media Lokal
Keyboard & IME:
  name: Papan Tik & IME
Online Media Player:
  name: Pemutar Media Daring
Social Network:
  name: Jaringan Sosial
