Ads:
  description: Esta aplicación contiene publicidad
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  description: Esta aplicación promueve complementos no gratuitos
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Esta aplicación contiene activos no libres
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Esta aplicación depende de otras aplicaciones no gratuitas
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Esta aplicación promueve servicios de red no gratuitos
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Esta aplicación realiza un seguimiento e informa de su actividad
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: El código fuente ascendente no es totalmente gratuito
  icon: ic_antifeature_upstreamnonfree.xml
