Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Conectividad
Development:
  name: Desarrollo
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Juegos
Graphics:
  name: Gráficos
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Dinero
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navegación
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Teléfono & SMS
Reading:
  name: Leyendo
Science & Education:
  name: Ciencia y Educación
Security:
  name: Seguridad
Sports & Health:
  name: Deportes & Salud
System:
  name: Sistema
Time:
  name: Hora
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Escribiendo
