Ads:
  description: Esta aplicação contém publicidade
  icon: ic_antifeature_ads.xml
  name: Anúncios
DisabledAlgorithm:
  description: Esta aplicação tem uma assinatura de segurança fraca
  icon: ic_antifeature_disabledalgorithm.xml
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: Esta aplicação contém uma falha de segurança conhecida
  icon: ic_antifeature_knownvuln.xml
  name: Vulnerabilidade conhecida
NSFW:
  description: Esta aplicação contém conteúdo que não deve ser divulgado ou visível
    em todos os lugares
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: O código-fonte já não está disponível e não é possível atualizar.
NonFreeAdd:
  description: Esta aplicação promove add-ons não livres
  icon: ic_antifeature_nonfreeadd.xml
  name: Complementos não livres
NonFreeAssets:
  description: Esta aplicação contém conteúdo não livre
  icon: ic_antifeature_nonfreeassets.xml
  name: Ativos não livres
NonFreeDep:
  description: Esta aplicação depende de aplicações não livres
  icon: ic_antifeature_nonfreedep.xml
  name: Dependências não livres
NonFreeNet:
  description: Esta aplicação promove serviços de rede não livres
  icon: ic_antifeature_nonfreenet.xml
  name: Serviços de rede não livres
Tracking:
  description: Esta aplicação monitoriza e reporta a sua atividade
  icon: ic_antifeature_tracking.xml
  name: Rastreamento
UpstreamNonFree:
  description: O código-fonte não é totalmente livre
  icon: ic_antifeature_upstreamnonfree.xml
  name: Upstream não livre
