Connectivity:
  name: Conectividade
Development:
  name: Desenvolvimento
Games:
  name: Jogos
Graphics:
  name: Gráficos
Internet:
  name: Internet
Money:
  name: Finanças
Multimedia:
  name: Multimédia
Navigation:
  name: Navegação
Phone & SMS:
  name: Telefone e SMS
Reading:
  name: Leitura
Science & Education:
  name: Ciência e educação
Security:
  name: Segurança
Sports & Health:
  name: Desporto e saúde
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempo
Writing:
  name: Escrita
App Store & Updater:
  name: Loja de apps e atualizador
Browser:
  name: Navegador
Calendar & Agenda:
  name: Calendário e agenda
Cloud Storage & File Sync:
  name: Armazenamento na nuvem e sincronização de ficheiros
DNS & Hosts:
  name: DNS & hosts
Email:
  name: E-mail
File Encryption & Vault:
  name: Criptografia de ficheiros e cofre
File Transfer:
  name: Transferência de ficheiros
Local Media Player:
  name: Reprodutor de média local
Messaging:
  name: Mensageiros
News:
  name: Notícias
Online Media Player:
  name: Reprodutor de média on-line
Password & 2FA:
  name: Palavras-passe e dois fatores
Podcast:
  name: Podcast
Social Network:
  name: Rede social
Voice & Video Chat:
  name: Chat de voz e vídeo
VPN & Proxy:
  name: VPN e proxy
Wallet:
  name: Carteira
Weather:
  name: Clima
