Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Conectividade
Development:
  name: Desenvolvimento
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Jogos
Graphics:
  name: Gráficos
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Finanças
Multimedia:
  name: Multimédia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navegação
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefone e SMS
Reading:
  name: Leitura
Science & Education:
  name: Ciência e educação
Security:
  name: Segurança
Sports & Health:
  name: Desporto e saúde
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempo
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Escrita
