Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Pripojiteľnosť
Development:
  name: Vývoj
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Hry
Graphics:
  name: Grafika
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Financie
Multimedia:
  name: Multimédiá
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigácia
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefón a SMS
Reading:
  name: Čítanie
Science & Education:
  name: Veda a výuka
Security:
  name: Bezpečnosť
Sports & Health:
  name: Šport & Zdravie
System:
  name: Systém
Theming:
  name: Témy
Time:
  name: Čas
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Písanie
