Ads:
  description: Bu uygulama reklam içerir
  name: Reklam
DisabledAlgorithm:
  description: Bu uygulamanın zayıf güvenlikli imzası var
  name: Güvenli Olmayan Bir Algoritma Kullanılarak İmzalandı
KnownVuln:
  description: Bu uygulama bilinen bir güvenlik açığı içerir
  name: Bilinen Güvenlik Açığı
NSFW:
  description: Bu uygulama, herkese duyurulmaması veya her yerde görünmemesi gereken
    içerik içeriyor
  name: NSFW
NoSourceSince:
  name: Kaynak kodu artık mevcut değil, güncelleme mümkün değil.
NonFreeAdd:
  description: Bu uygulama özgür olmayan eklentilere teşvik eder
  name: Özgür Olmayan Eklentiler
NonFreeAssets:
  description: Bu uygulama özgür olmayan unsurlar içerir
  name: Özgür Olmayan İçerikler
NonFreeDep:
  description: Bu uygulama özgür olmayan başka uygulamalara bağımlıdır
  name: Özgür Olmayan Bağlılıklar
NonFreeNet:
  description: Bu uygulama özgür olmayan ağ hizmetlerine teşvik eder
  name: Özgür Olmayan Ağ Hizmetleri
Tracking:
  description: Bu uygulama etkinliğinizi izler ve bildirir
  name: İzleme
UpstreamNonFree:
  description: Kaynak kod tamamen özgür değildir
  name: Üst Kod Özgür Değil
