Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Bağlanabilirlik
Development:
  name: Geliştirme
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Oyunlar
Graphics:
  name: Çizim
Internet:
  name: İnternet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Finans
Multimedia:
  name: Çoklu ortam
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigasyon
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon ve SMS
Reading:
  name: Okuma
Science & Education:
  name: Bilim ve eğitim
Security:
  name: Güvenlik
Sports & Health:
  name: Spor ve Sağlık
System:
  name: Sistem
Theming:
  name: Tema
Time:
  name: Zaman
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Yazım
