Connectivity:
  name: Bağlanabilirlik
  icon: category_connectivity.png
Development:
  name: Geliştirme
  icon: category_development.png
Games:
  name: Oyunlar
  icon: category_games.png
Graphics:
  name: Çizim
  icon: category_graphics.png
Internet:
  name: İnternet
  icon: category_internet.png
Money:
  name: Finans
  icon: category_money.png
Multimedia:
  name: Çoklu ortam
Navigation:
  name: Navigasyon
Phone & SMS:
  name: Telefon ve SMS
Reading:
  name: Okuma
  icon: category_reading.png
Science & Education:
  name: Bilim ve eğitim
  icon: category_science_education.png
Security:
  name: Güvenlik
  icon: category_security.png
Sports & Health:
  name: Spor ve Sağlık
System:
  name: Sistem
  icon: category_system.png
Theming:
  name: Tema
  icon: category_theming.png
Time:
  name: Zaman
Writing:
  name: Yazım
  icon: category_writing.png
