Ads:
  description: Þetta forrit inniheldur auglýsingar
  icon: ic_antifeature_ads.xml
  name: Auglýsingar
DisabledAlgorithm:
  description: Þetta forrit er með veika öryggisundirritun
  icon: ic_antifeature_disabledalgorithm.xml
  name: Undirritað með óöruggu reikniriti
KnownVuln:
  description: Þetta forrit inniheldur þekktan öryggisveikleika
  icon: ic_antifeature_knownvuln.xml
  name: Þekktir veikleikar
NSFW:
  description: Þetta forrit inniheldur efni sem ekki ætti að gefa út eða birta opinberlega
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Grunnkóðinn er ekki lengur tiltækur, engar uppfærslur eru mögulegar.
NonFreeAdd:
  description: Þetta forrit ýtir undir notkun ófrjálsra viðbóta
  icon: ic_antifeature_nonfreeadd.xml
  name: Ófrjálsar viðbætur
NonFreeAssets:
  description: Þetta forrit inniheldur ófrjáls tilföng
  icon: ic_antifeature_nonfreeassets.xml
  name: Ófrjáls tilföng
NonFreeDep:
  description: Þetta forrit er háð öðrum ófrjálsum forritum
  icon: ic_antifeature_nonfreedep.xml
  name: Ófrjálsar kerfiskröfur
NonFreeNet:
  description: Þetta forrit ýtir undir notkun ófrjálsrar þjónustu
  icon: ic_antifeature_nonfreenet.xml
  name: Ófrjálsar netþjónustur
Tracking:
  description: Þetta forrit fylgist með og gefur skýrslu um hegðun þína
  icon: ic_antifeature_tracking.xml
  name: Eftirlit
UpstreamNonFree:
  description: Grunnkóði útgefanda er ekki fullkomlega frjáls
  icon: ic_antifeature_upstreamnonfree.xml
  name: Uppruni ófrjáls
