Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Tengingar
Development:
  name: Þróun
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Leikir
Graphics:
  name: Myndefni
Internet:
  name: Internetið
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Fjármál
Multimedia:
  name: Margmiðlun
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Yfirsýn
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Símar og SMS
Reading:
  name: Lestur
Science & Education:
  name: Menntun og vísindi
Security:
  name: Öryggi
Sports & Health:
  name: Íþróttir og heilsa
System:
  name: Kerfið
Theming:
  name: Þemu
Time:
  name: Tími
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skrifa
