Ads:
  description: Este aplicativo contém anúncios
  icon: ic_antifeature_ads.xml
  name: Anúncios
DisabledAlgorithm:
  description: Este aplicativo tem uma assinatura de segurança fraca
  icon: ic_antifeature_disabledalgorithm.xml
  name: Assinado Usando um Algoritmo Inseguro
KnownVuln:
  description: Este aplicativo contém uma falha de segurança já conhecida
  icon: ic_antifeature_knownvuln.xml
  name: Vulnerabilidade conhecida
NSFW:
  description: Este aplicativo contém conteúdo impróprio para menores de idade
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Não é possível atualizar, o código fonte não está mais disponível.
NonFreeAdd:
  description: Este aplicativo promove complementos não livres
  icon: ic_antifeature_nonfreeadd.xml
  name: Complementos não livres
NonFreeAssets:
  description: Este aplicativo contém conteúdo não livre
  icon: ic_antifeature_nonfreeassets.xml
  name: Conteúdos não livres
NonFreeDep:
  description: Este aplicativo depende de aplicativos não livres
  icon: ic_antifeature_nonfreedep.xml
  name: Dependências não livres
NonFreeNet:
  description: Este aplicativo promove serviços de rede não livres
  icon: ic_antifeature_nonfreenet.xml
  name: Serviços de rede não livres
Tracking:
  description: Este aplicativo rastreia e relata sua atividade
  icon: ic_antifeature_tracking.xml
  name: Rastreamento
UpstreamNonFree:
  description: O código fonte original não é totalmente livre
  icon: ic_antifeature_upstreamnonfree.xml
  name: Upstream não livre
