Connectivity:
  name: Conectividade
  icon: category_connectivity.png
Development:
  name: Desenvolvimento
  icon: category_development.png
Games:
  name: Jogos
  icon: category_games.png
Graphics:
  name: Gráficos
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Finanças
  icon: category_money.png
Multimedia:
  name: Multimédia
Navigation:
  name: Navegação
  icon: category_navigation.png
Phone & SMS:
  name: Telefone e SMS
Reading:
  name: Leitura
  icon: category_reading.png
Science & Education:
  name: Ciência e educação
  icon: category_science_education.png
Security:
  name: Segurança
  icon: category_security.png
Sports & Health:
  name: Desporto e saúde
System:
  name: Sistema
  icon: category_system.png
Theming:
  name: Temas
  icon: category_theming.png
Time:
  name: Tempo
Writing:
  name: Escrita
  icon: category_writing.png
