Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Connectivitat
Development:
  name: Desenvolupament
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Jocs
Graphics:
  name: Gràfics
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Diners
Multimedia:
  name: Multimèdia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navegació
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Mòbil i missatgeria
Reading:
  name: Lectura
Science & Education:
  name: Ciència i educació
Security:
  name: Seguretat
Sports & Health:
  name: Esports i Salut
System:
  name: Sistema
Theming:
  name: Temes
Time:
  name: Temps
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Per a escriure
