Ads:
  icon: ic_antifeature_ads.xml
Development:
  name: विकास
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: खेलहरू
Graphics:
  name: ग्राफिक्स
Internet:
  name: इन्टरनेट
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: पैसा
Multimedia:
  name: मल्टिमेडिया
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: नेभिगेसन
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: फोन र एसएमएस
Reading:
  name: पढ्दै
Science & Education:
  name: विज्ञान र शिक्षा
Security:
  name: सुरक्षा
Time:
  name: समय
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: लेखन
