Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Connectiviteit
Development:
  name: Ontwikkeling
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spellen
Graphics:
  name: Grafisch
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Geld
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigatie
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefoon & SMS
Reading:
  name: Lezen
Science & Education:
  name: Onderwijs & wetenschap
Security:
  name: Beveiliging
Sports & Health:
  name: Sport & gezondheid
System:
  name: Systeem
Theming:
  name: Thema\'s
Time:
  name: Tijd
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Schrijven
