Ads:
  description: Deze app bevat advertenties
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Deze app heeft een zwakke beveiligingshandtekening
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Deze app bevat een bekende beveiligingskwetsbaarheid
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: De broncode is niet meer beschikbaar, updates zijn niet mogelijk.
NonFreeAdd:
  description: Deze app promoot niet-vrije add-ons
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Deze app bevat niet-vrije elementen
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Deze app vereist andere niet-vrije apps
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Deze app promoot niet-vrije netwerkdiensten
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Deze app houdt je activiteiten bij en rapporteert ze
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: De stroomopwaartse broncode is niet helemaal vrij
  icon: ic_antifeature_upstreamnonfree.xml
