Connectivity:
  name: Зв'язок
  icon: category_connectivity.png
Development:
  name: Розробка
  icon: category_development.png
Games:
  name: Ігри
  icon: category_games.png
Graphics:
  name: Графіка
  icon: category_graphics.png
Internet:
  name: Інтернет
  icon: category_internet.png
Money:
  name: Фінанси
  icon: category_money.png
Multimedia:
  name: Мультимедіа
Navigation:
  name: Навігація
  icon: category_navigation.png
Phone & SMS:
  name: Телефон і SMS
Reading:
  name: Читання
  icon: category_reading.png
Science & Education:
  name: Освіта й наука
  icon: category_science_education.png
Security:
  name: Безпека
  icon: category_security.png
Sports & Health:
  name: Спорт і здоров'я
System:
  name: Система
  icon: category_system.png
Theming:
  name: Тематика
  icon: category_theming.png
Time:
  name: Час
Writing:
  name: Написання
  icon: category_writing.png
Email:
  name: Електронна пошта
VPN & Proxy:
  name: VPN та проксі
DNS & Hosts:
  name: DNS та хости
Password & 2FA:
  name: Пароль і двофакторна автентифікація
Social Network:
  name: Соціальна мережа
File Transfer:
  name: Передавання файлів
File Encryption & Vault:
  name: Шифрування файлів та сховище
Messaging:
  name: Повідомлення
App Store & Updater:
  name: App Store та оновлення
Browser:
  name: Браузер
Local Media Player:
  name: Локальний медіаплеєр
News:
  name: Новини
Weather:
  name: Погода
Online Media Player:
  name: Онлайн-медіаплеєр
Keyboard & IME:
  name: Клавіатура та редактор вхідних даних
Podcast:
  name: Подкаст
Voice & Video Chat:
  name: Голосовий та відеочат
Cloud Storage & File Sync:
  name: Хмарне сховище та синхронізація файлів
Wallet:
  name: Гаманець
Calendar & Agenda:
  name: Календар і порядок денний
Bookmark:
  name: Закладка
Calculator:
  name: Калькулятор
Draw:
  name: Нічия
Ebook Reader:
  name: Зчитувач електронних книг
Finance Manager:
  name: Фінансовий менеджер
Gallery:
  name: Галерея
Icon Pack:
  name: Набір значків
Launcher:
  name: Запуск
Note:
  name: Примітка
Pass Wallet:
  name: Гаманець Pass
Recipe Manager:
  name: Менеджер рецептів
Text Editor:
  name: Текстовий редактор
Translation & Dictionary:
  name: Переклад і словник
Unit Convertor:
  name: Конвертер одиниць
Wallpaper:
  name: Шпалери
Workout:
  name: Тренування
Public Transport Map & Timetable:
  name: Карта та розклад руху громадського транспорту
Task:
  name: Завдання
Shopping List:
  name: Список покупок
