Connectivity:
  name: Зв\'язок
  icon: category_connectivity.png
Development:
  name: Розробка
  icon: category_development.png
Games:
  name: Ігри
  icon: category_games.png
Graphics:
  name: Графіка
  icon: category_graphics.png
Internet:
  name: Інтернет
  icon: category_internet.png
Money:
  name: Фінанси
  icon: category_money.png
Multimedia:
  name: Мультимедіа
Navigation:
  name: Навігація
  icon: category_navigation.png
Phone & SMS:
  name: Телефон і SMS
Reading:
  name: Читання
  icon: category_reading.png
Science & Education:
  name: Освіта й наука
  icon: category_science_education.png
Security:
  name: Безпека
  icon: category_security.png
Sports & Health:
  name: Спорт і здоров\'я
System:
  name: Система
  icon: category_system.png
Theming:
  name: Тематика
  icon: category_theming.png
Time:
  name: Час
Writing:
  name: Написання
  icon: category_writing.png
