repo:
  description: Офіційний репозиторій вільного програмного забезпечення F-Droid. Усе в ньому завжди збирається з джерельного коду.
  icon: fdroid-icon.png
  name: F-Droid
archive:
  icon: fdroid-icon.png
  name: Архів F-Droid
  description: Архів офіційного репозиторію вільного програмного забезпечення F-Droid. Застосунки в ньому застарілі й можуть містити відомі вразливості та проблеми з безпекою!
