Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Свързаност
Development:
  name: Разработка
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Игри
Graphics:
  name: Изображения
Internet:
  name: Интернет
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Финанси
Multimedia:
  name: Мултимедия
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Местоположение
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Телефон и SMS
Reading:
  name: Четене
Science & Education:
  name: Наука и образование
Security:
  name: Сигурност
Sports & Health:
  name: Спорт и здраве
System:
  name: Системни
Theming:
  name: Теми
Time:
  name: Управление на времето
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Писане
