Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Girêdanî
Development:
  name: Pêşdebirin
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Lîsk
Graphics:
  name: Grafîk
Internet:
  name: Înternet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Diravî
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Xwendin
Science & Education:
  name: Zanist & perwerde
Security:
  name: Ewlehî
Sports & Health:
  name: Werzişî & tenduristî
System:
  name: Pergal
Time:
  name: Dem
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Nivîsandin
