Ads:
  description: Оваа апликација содржи реклами
  icon: ic_antifeature_ads.xml
  name: Реклами
DisabledAlgorithm:
  description: Оваа апликација има слаб безбедносен потпис
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Оваа апликација содржи позната безбедносна ранливост
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Изворниот код повеќе не е достапен, не се можни ажурирања.
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Оваа апликација ја следи и јавува вашата активност
  icon: ic_antifeature_tracking.xml
  name: Следење
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
