Ads:
  description: ဒီ app သည္ ေၾကျငာမ်ားပါဝင္သည္
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ေနာက္ထပ္ပါဝင္သည့္အရာမ်ားပါဝင္သည္
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ပံုမ်ားပါဝင္သည္
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: ဒီ app သည္ တျခားအခမဲ့မဟုတ္ေသာ app မ်ားေပၚမူတည္သည္
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာကြန္ရက္ ဝန္ေဆာင္မႈကိုေထာက္ပံ့သည္
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: ဒီ app သည္ သင့္လႈပ္ရွားမႈမ်ားကိုလိုက္ၾကည့္ျပီးမွတ္တမ္း မွတ္သည္
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: ဆိုစ့္ကုဒ္သည္ လံုးဝအခမဲ့မဟုတ္ပါ
  icon: ic_antifeature_upstreamnonfree.xml
