Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Kapcsolódás
Development:
  name: Fejlesztés
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Játékok
Graphics:
  name: Grafika
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Pénzügyek
Multimedia:
  name: Multimédia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigáció
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon és SMS
Reading:
  name: Olvasás
Science & Education:
  name: Tudomány és oktatás
Security:
  name: Biztonság
Sports & Health:
  name: Sport és egészség
System:
  name: Rendszer
Theming:
  name: Stílus
Time:
  name: Idő
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Írás
