Ads:
  description: Šioje programėlėje yra reklamų
  icon: ic_antifeature_ads.xml
  name: Skelbimai
DisabledAlgorithm:
  description: Ši programėlė turi silpną saugumo parašą
  icon: ic_antifeature_disabledalgorithm.xml
  name: Pasirašyta naudojant nesaugų algoritmą
KnownVuln:
  description: Šioje programėlėje yra žinomas saugumo pažeidžiamumas
  icon: ic_antifeature_knownvuln.xml
  name: Žinomas pažeidžiamumas
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Pirminis kodas daugiau nebeprieinamas, atnaujinimai negalimi.
NonFreeAdd:
  description: Ši programėlė skatina įdiegti nelaisvus papildinius
  icon: ic_antifeature_nonfreeadd.xml
  name: Ne atviro kodo papildiniai
NonFreeAssets:
  description: Šioje programėlėje yra nelaisvų resursų
  icon: ic_antifeature_nonfreeassets.xml
  name: Ne atviro kodo resursai
NonFreeDep:
  description: Ši programėlė priklauso nuo nelaisvų programėlių
  icon: ic_antifeature_nonfreedep.xml
  name: Ne atviro kodo priklausomieji
NonFreeNet:
  description: Ši programėlė skatina nelaisvas tinklo paslaugas
  icon: ic_antifeature_nonfreenet.xml
  name: Ne atviro kodo tinklo paslaugos
Tracking:
  description: Ši programėlė seka ir perduoda Jūsų veiksmus
  icon: ic_antifeature_tracking.xml
  name: Sekimas
UpstreamNonFree:
  description: Pradinis pirminis kodas nėra visiškai laisvas
  icon: ic_antifeature_upstreamnonfree.xml
  name: Ne atviro kodo pradinis kodas
