Ads:
  description: Šioje programėlėje yra reklamų
  name: Skelbimai
DisabledAlgorithm:
  description: Ši programėlė turi silpną saugumo parašą
  name: Pasirašyta naudojant nesaugų algoritmą
KnownVuln:
  description: Šioje programėlėje yra žinomas saugumo pažeidžiamumas
  name: Žinomas pažeidžiamumas
NSFW:
  description: Šioje programoje yra turinio, kuris neturėtų būti viešinamas ar visur matomas
  name: „NSFW“
NoSourceSince:
  name: Nebėra šaltinio
  description: Šaltinio kodas nebeprieinamas, atnaujinimai negalimi
NonFreeAdd:
  description: Ši programėlė propaguoja ne laisvosios programinės įrangos papildinius
  name: Ne atviro kodo papildiniai
NonFreeAssets:
  description: Šioje programėlėje yra mokamų resursų
  name: Mokami resursai
NonFreeDep:
  description: Ši programėlė priklauso nuo kitų uždaro kodo programėlių
  name: Nuo uždaro kodo priklausomos programėlės
NonFreeNet:
  description: Ši programėlė propaguoja privačią tinklo paslaugą arba nuo jos priklauso
  name: Ne atviro kodo tinklo paslaugos
Tracking:
  description: Ši programėlė seka ir perduoda jūsų veiklą
  name: Sekimas
TetheredNet:
  description: Ši programėlė visiškai priklauso nuo tam tikro tinklo paslaugos atvejo
  name: Pririšto tinklo paslaugos
