Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Ryšiai ir tinklas
Development:
  name: Plėtojimas
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Žaidimai
Graphics:
  name: Grafika
Internet:
  name: Internetas
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Pinigai
Multimedia:
  name: Multimedija
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigacija
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefonas ir SMS
Reading:
  name: Skaitymas
Science & Education:
  name: Mokslas ir švietimas
Security:
  name: Saugumas
Sports & Health:
  name: Sportas ir sveikata
System:
  name: Sistema
Theming:
  name: Apipavidalinimas
Time:
  name: Laikas
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Rašymas
