archive:
  description: Oficialios F-Droid laisvosios programinės įrangos saugyklos archyvas. Čia esančios programos yra senos ir jose gali būti žinomų pažeidžiamumų ir saugumo problemų!
  name: F-Droid archyvas
repo:
  description: Oficiali F-Droid laisvosios programinės įrangos saugykla. Visa, kas yra šioje saugykloje, yra sukurta iš šaltinio kodo.
  name: F-Droid
