Ads:
  description: Selles rakenduses on reklaame
  name: Reklaamid
DisabledAlgorithm:
  description: Sellel rakendusel on nõrk turvasignatuur
  name: Allkirjastamisel on kasutatud ebaturvalist algoritmi
KnownVuln:
  description: Sellel rakendusel on tuntud turvanõrkus
  name: Tuntud turvanõrkus
NSFW:
  description: Selles rakenduses on sisu, mida ei saa kõikjal avaldada ega peaks olema
    kõikjalt vaadatav
  name: NSFW
NoSourceSince:
  name: Lähtekood ei ole enam saadaval, uuendused ei ole enam võimalikud.
NonFreeAdd:
  description: See rakendus edendab mitte-vabu laiendusi
  name: Mitte-vabad laiendused
NonFreeAssets:
  description: Selles rakenduses on mitte-vabu komponente
  name: Mitte-vabad komponendid
NonFreeDep:
  description: See rakendus sõltub teistest mitte-vabadest rakendustest
  name: Sõltuvus mitte-vabadest rakendustest
NonFreeNet:
  description: See rakendus eelistab mitte-vabu võrguteenuseid
  name: Mitte-vabad võrguteenuseid
Tracking:
  description: See rakendus jälgib ja raporteerib su aktiivsusest
  name: Sisaldab kasutajate tegevuse jälgimist
UpstreamNonFree:
  description: Ülesvoolu lähtekood ei ole täiesti vaba
  name: Mitte-vaba ülesvoolu lähtekood
