Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Ühenduvus
Development:
  name: Arendus
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Mängud
Graphics:
  name: Graafika
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Raha
Multimedia:
  name: Multimeedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigeerimine
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Lugemine
Science & Education:
  name: Teadus & haridus
Security:
  name: Turvalisus
Sports & Health:
  name: Sport & tervis
System:
  name: Süsteem
Theming:
  name: Teemad
Time:
  name: Aeg
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Kirjutamine
