Ads:
  description: Apu hili lina matangazo
  name: Matangazo
DisabledAlgorithm:
  description: Apu hii ina saini dhaifu ya usalama
KnownVuln:
  description: Apu hii ina athari inayojulikana ya usalama
NSFW:
  description: Apu hii ina maudhui ambayo hayafai kutangazwa au kuonekana kila mahali
Tracking:
  name: Fuatilia
