Ads:
  description: Apu hili lina matangazo
  name: Matangazo
DisabledAlgorithm:
  description: Apu hili lina sahihi wa usalama dhaifu
KnownVuln:
  description: Apu hili lina julikana kuwa na usalama isiolindwa
NSFW:
  description: Apu hili lina maudhui isiyofaa kutangazwa au kuonekana wazi pahali popote
Tracking:
  name: Fuatilia
