archive:
  description: Kumbukumbu hio ya hazina rasmi ya apu huru ya F-Droid. Api hapa ni mzee na inaweza kuwa na udhaifu na masuala ya kiusalama!
  name: Kumbukumbu ya F-Droid
repo:
  description: Hazina rasmi ya Programu huru ya F-Droid. Kila kitu katika ghala hii inaundwa kila mara kutoka kwa msimbo wa chanzo.
  name: F-Droid
