Connectivity:
  name: Conectividade
  icon: categoria_conectividade.png
Development:
  name: Desenvolvimento
  icon: categoria_desenvolvimento.png
Games:
  name: Jogos
  icon: categoria_jogos.png
Graphics:
  name: Gráficos
  icon: categoria_graficos.png
Internet:
  name: Internet
  icon: categoria_internet.png
Money:
  name: Finanças
  icon: categoria_dinheiro.png
Multimedia:
  name: Multimédia
Navigation:
  name: Navegação
  icon: categoria_navegação.png
Phone & SMS:
  name: Telefone e SMS
Reading:
  name: Leitura
  icon: categoria_leitura.png
Science & Education:
  name: Ciência e educação
  icon: categoria_ciencia_educação.png
Security:
  name: Segurança
  icon: categoria_segurança.png
Sports & Health:
  name: Desporto e saúde
System:
  name: Sistema
  icon: categoria_sistema.png
Theming:
  name: Temas
  icon: categoria_temas.png
Time:
  name: Tempo
Writing:
  name: Escrita
  icon: categoria_escrita.png
App Store & Updater:
  name: Loja de apps e atualizador
Bookmark:
  name: Marcador
Browser:
  name: Navegador
Calculator:
  name: Calculador
Calendar & Agenda:
  name: Calendário e agenda
Cloud Storage & File Sync:
  name: Armazenamento na nuvem e sincronização de ficheiros
DNS & Hosts:
  name: DNS & hosts
Draw:
  name: Desenhar
Ebook Reader:
  name: Leitor de e-book
Email:
  name: E-mail
File Encryption & Vault:
  name: Criptografia de ficheiros e cofre
File Transfer:
  name: Transferência de ficheiros
Finance Manager:
  name: Gestor de finanças
Gallery:
  name: Galeria
Icon Pack:
  name: Pacote de ícones
Local Media Player:
  name: Reprodutor de média local
Messaging:
  name: Mensageiros
News:
  name: Notícias
Note:
  name: Nota
Online Media Player:
  name: Reprodutor de média on-line
Pass Wallet:
  name: Carteira de passe
Password & 2FA:
  name: Palavras-passe e dois fatores
Podcast:
  name: Podcast
Public Transport Map & Timetable:
  name: Mapa de transporte público e horários
Recipe Manager:
  name: Gestor de receitas
Shopping List:
  name: Lista de compras
Social Network:
  name: Rede social
Task:
  name: Tarefa
Text Editor:
  name: Editor de textos
Translation & Dictionary:
  name: Tradução e dicionário
Unit Convertor:
  name: Conversor de unidades
Voice & Video Chat:
  name: Chat de voz e vídeo
VPN & Proxy:
  name: VPN e proxy
Wallet:
  name: Carteira
Weather:
  name: Clima
Keyboard & IME:
  name: Teclado e MDE (IME)
Launcher:
  name: Lançador
Wallpaper:
  name: Papel de parede
Workout:
  name: Exercício físico
