Connectivity:
  name: 접속성
Development:
  name: 개발
Games:
  name: 게임
Graphics:
  name: 그래픽
Internet:
  name: 인터넷
Money:
  name: 금융
Multimedia:
  name: 멀티미디어
Navigation:
  name: 네비게이션
Phone & SMS:
  name: 전화 및 문자
Reading:
  name: 독서
Science & Education:
  name: 과학 및 교육
Security:
  name: 보안
Sports & Health:
  name: 스포츠 및 건강
System:
  name: 시스템
Theming:
  name: 꾸미기
Time:
  name: 시간
Writing:
  name: 작성
App Store & Updater:
  name: 앱 스토어 및 업데이터
Bookmark:
  name: 북마크
Browser:
  name: 브라우저
Calculator:
  name: 계산기
Calendar & Agenda:
  name: 캘린더 및 일정
Cloud Storage & File Sync:
  name: 클라우드 저장소 및 파일 동기화
DNS & Hosts:
  name: DNS 및 호스트
Draw:
  name: 그리기
Ebook Reader:
  name: 전자책 리더
Email:
  name: 이메일
File Encryption & Vault:
  name: 파일 암호화 및 보관
File Transfer:
  name: 파일 전송
Finance Manager:
  name: 재무 관리자
Gallery:
  name: 갤러리
Icon Pack:
  name: 아이콘 팩
Keyboard & IME:
  name: 키보드 및 IME
Launcher:
  name: 런처
Local Media Player:
  name: 로컬 미디어 플레이어
Messaging:
  name: 메시지
News:
  name: 뉴스
Note:
  name: 메모
Online Media Player:
  name: 온라인 미디어 플레이어
Pass Wallet:
  name: 패스 지갑
Password & 2FA:
  name: 비밀번호 및 2단계 인증
Podcast:
  name: 팟캐스트
Public Transport:
  name: 대중교통 지도 및 시간표
Recipe Manager:
  name: 레시피 관리자
Shopping List:
  name: 쇼핑 목록
Social Network:
  name: 소셜 네트워크
Task:
  name: 작업
Text Editor:
  name: 텍스트 편집기
Translation & Dictionary:
  name: 번역 및 사전
Unit Convertor:
  name: 단위 변환기
Voice & Video Chat:
  name: 음성 및 영상 채팅
VPN & Proxy:
  name: VPN 및 프록시
Wallet:
  name: 지갑
Wallpaper:
  name: 배경화면
Weather:
  name: 날씨
Workout:
  name: 운동
