Connectivity:
  name: Łączność
Development:
  name: Rozwój
Games:
  name: Gry
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Finanse
Multimedia:
  name: Multimedia
Navigation:
  name: Nawigacja
Phone & SMS:
  name: Telefon i SMS
Reading:
  name: Czytanie
Science & Education:
  name: Nauka i edukacja
Security:
  name: Bezpieczeństwo
Sports & Health:
  name: Sport i zdrowie
System:
  name: System
Theming:
  name: Motywy
Time:
  name: Czas
Writing:
  name: Pisanie
Email:
  name: E-mail
VPN & Proxy:
  name: VPN i Proxy
DNS & Hosts:
  name: DNS i hosty
File Encryption & Vault:
  name: Szyfrowanie plików i sejf
Password & 2FA:
  name: Hasła i uwierzytelnianie dwuskładnikowe (2FA)
Offline Music & Video Player:
  name: Odtwarzacz muzyki i wideo offline
Messaging:
  name: Wiadomości
File Transfer:
  name: Przesyłanie plików
Social Network:
  name: Sieć społecznościowa
App Store & Updater:
  name: App Store i narzędzie do aktualizacji
Browser:
  name: Przeglądarka
Local Media Player:
  name: Lokalny odtwarzacz multimediów
News:
  name: Wiadomości
Online Media Player:
  name: Odtwarzacz multimediów online
