Connectivity:
  name: Łączność
  icon: category_connectivity.png
Development:
  name: Programowanie
  icon: category_development.png
Games:
  name: Gry
  icon: category_games.png
Graphics:
  name: Grafika
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Finanse
  icon: category_money.png
Multimedia:
  name: Multimedia
Navigation:
  name: Nawigacja
Phone & SMS:
  name: Telefon i SMS
Reading:
  name: Czytanie
  icon: category_reading.png
Science & Education:
  name: Nauka i edukacja
  icon: category_science_education.png
Security:
  name: Bezpieczeństwo
  icon: category_security.png
Sports & Health:
  name: Sport i zdrowie
System:
  name: System
  icon: category_system.png
Theming:
  name: Motywy
  icon: category_theming.png
Time:
  name: Czas
Writing:
  name: Pisanie
  icon: category_writing.png
