archive:
  description: Archiwum oficjalnego repozytorium wolnego oprogramowania F-Droid. Aplikacje tutaj są stare i mogą zawierać znane luki w zabezpieczeniach oraz mieć problemy z bezpieczeństwem!
  icon: fdroid-logo.png
  name: Archiwum F-Droid
repo:
  description: Oficjalne repozytorium wolnego oprogramowania F-Droid. Wszystko w tym repozytorium jest zawsze zbudowane z kodu źródłowego.
  icon: fdroid-logo.png
  name: F-Droid
