Ads:
  description: इस एप्लिकेशन में विज्ञापन शामिल हैं
  name: विज्ञापन
DisabledAlgorithm:
  description: इस ऐप में गैर-मुक्त संपत्ति है
  name: असुरक्षित एल्गोरिदम का उपयोग करके हस्ताक्षरित
KnownVuln:
  description: इस एप्लिकेशन में एक ज्ञात सुरक्षा भेद्यता है
  name: ज्ञात भेद्यता
NoSourceSince:
  name: स्रोत कोड अब उपलब्ध नहीं है, कोई अद्यतन संभव नहीं है।
NonFreeAdd:
  description: यह ऐप नॉन-फ्री ऐड-ऑन को बढ़ावा देता है
  name: गैर-मुक्त एडॉन्स
NonFreeAssets:
  description: इस ऐप में गैर-मुक्त संपत्ति है
  name: गैर-मुक्त Assets
NonFreeDep:
  description: यह ऐप अन्य नॉन-फ्री ऐप पर निर्भर करता है
  name: गैर-मुक्त निर्भरताएं
NonFreeNet:
  description: यह ऐप गैर-मुक्त नेटवर्क सेवाओं को बढ़ावा देता है
  name: गैर-मुक्त नेटवर्क सेवाएं
Tracking:
  description: यह एप्प आपकी गतिविधि पर नज़र रखती है और रिपोर्ट करती है
  name: नज़र रखना
UpstreamNonFree:
  description: अपस्ट्रीम सोर्स कोड पूरी तरह से फ्री नहीं है
  name: अपस्ट्रीम गैर-मुक्त
