Ads:
  description: Naglalaman ng patalastas ang app na ito
  icon: ic_antifeature_ads.xml
  name: Mga Ad
DisabledAlgorithm:
  description: May mahinang pirmang panseguridad ang app na ito
  icon: ic_antifeature_disabledalgorithm.xml
  name: Pirmado gamit ang isang di-ligtas na algoritmo
KnownVuln:
  description: Naglalaman ng isang kilalang kahinaan sa seguridad ang app na ito
  icon: ic_antifeature_knownvuln.xml
  name: May Kahinaan
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Wala na yung source code, di na itong muling maia-update.
NonFreeAdd:
  description: Nagpo-promote ng mga di-libreng addon ang app na ito
  icon: ic_antifeature_nonfreeadd.xml
  name: Mga di-libreng addon
NonFreeAssets:
  description: Naglalaman ng mga di-libreng asset ang app na ito
  icon: ic_antifeature_nonfreeassets.xml
  name: Mga di-libreng asset
NonFreeDep:
  description: Dumedepende sa ibang mga di-libreng app ang app na ito
  icon: ic_antifeature_nonfreedep.xml
  name: Dumedepende sa mga di-libre
NonFreeNet:
  description: Nagpo-promote ng mga di-libreng serbisyong pang-network ang app na
    ito
  icon: ic_antifeature_nonfreenet.xml
  name: Mga di-libre serbisyong pang-network
Tracking:
  description: Tina-track at inuulat ng app na ito ang iyong aktibidad
  icon: ic_antifeature_tracking.xml
  name: Pagta-track
UpstreamNonFree:
  description: Di talaga malaya ang upstream source code
  icon: ic_antifeature_upstreamnonfree.xml
  name: Di-libreng upstream
