Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Konektibidad
Development:
  name: Pagde-develop
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Laro
Graphics:
  name: Grapiks
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Pananalapi
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Nabigasyon
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Tawag & Text
Reading:
  name: Pagbabasa
Science & Education:
  name: Agham & Edukasyon
Security:
  name: Seguridad
Sports & Health:
  name: Palakasan & Kalusugan
System:
  name: Sistema
Theming:
  name: Pagtetema
Time:
  name: Oras
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Pagsusulat
