Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Connectivité
Development:
  name: Développement
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Jeux
Graphics:
  name: Graphisme
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Finances
Multimedia:
  name: Multimédia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigation
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Téléphone et SMS
Reading:
  name: Lecture
Science & Education:
  name: Science et éducation
Security:
  name: Sécurité
Sports & Health:
  name: Sport et santé
System:
  name: Système
Theming:
  name: Personnalisation
Time:
  name: Temps
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Écriture
