Connectivity:
  name: Connectivité
Development:
  name: Développement
Games:
  name: Jeux
Graphics:
  name: Graphisme
Internet:
  name: Internet
Money:
  name: Finances
Multimedia:
  name: Multimédia
Navigation:
  name: Navigation
Phone & SMS:
  name: Téléphone et SMS
Reading:
  name: Lecture
Science & Education:
  name: Science et éducation
Security:
  name: Sécurité
Sports & Health:
  name: Sport et santé
System:
  name: Système
Theming:
  name: Personnalisation
Time:
  name: Temps
Writing:
  name: Écriture
Calendar & Agenda:
  name: Calendrier & Agenda
Cloud Storage & File Sync:
  name: Stockage dans le cloud & Synchronisation de fichiers
Messaging:
  name: Messagerie
News:
  name: Nouvelles
Social Network:
  name: Réseau social
Wallet:
  name: Portefeuille
Voice & Video Chat:
  name: Chat vocal & vidéo
Online Media Player:
  name: Lecteur Multimédia en Ligne
Password & 2FA:
  name: Mot de passe & 2FA
Podcast:
  name: Podcast
Weather:
  name: Météo
VPN & Proxy:
  name: VPN & Proxy
DNS & Hosts:
  name: DNS & Hôtes
Email:
  name: E-mail
App Store & Updater:
  name: App Store et Programme de mise à jour
Browser:
  name: Navigateur
File Encryption & Vault:
  name: Cryptage de fichiers & Coffre-fort
File Transfer:
  name: Transfert de fichiers
Keyboard & IME:
  name: Clavier & IME
Local Media Player:
  name: Lecteur Multimédia Local
