Ads:
  description: Ova aplikacija sadržava oglase
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Ova aplikacija ima slab sigurnosni potpis
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: Ova aplikacija sadrži poznatu sigurnosnu ranjivost
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Izvorni kod više nije dostupan, nije moguće ažurirati.
NonFreeAdd:
  description: Ova aplikacija promovira neslobodne dodatke
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Ova aplikacija sadrži neslobodne resurse
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Ova aplikacija ovisi o drugim neslobodnim aplikacijama
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Ova aplikacija promovira neslobodne mrežne usluge
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Ova aplikacija prati i javlja Vašu aktivnost
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: Uzvodni izvorni kod nije u potpunosti otvoren/slobodan
  icon: ic_antifeature_upstreamnonfree.xml
