Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Povezivanje
Development:
  name: Razvoj
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Igre
Graphics:
  name: Grafika
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Novac
Multimedia:
  name: Multimedija
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigacija
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon i SMS
Reading:
  name: Čitanje
Science & Education:
  name: Znanost i edukacija
Security:
  name: Sigurnost
Sports & Health:
  name: Sport i zdravlje
System:
  name: Sustav
Theming:
  name: Teme
Time:
  name: Vrijeme
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Pisanje
