Ads:
  description: Asnas-a yegber adellel
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: Asnas-a yesɛa azmul i ixuṣṣen deg tɣellist
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Tangalt taɣbalut dayen ur telli ara, ulac ileqman.
NonFreeAdd:
  description: Asnas-a yegber Izegrar ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: Asnas-a yegber iḥricen ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: Asnas-a icudd ɣer yisnasen-nniḍen ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: Asnas-a isnernay imeẓliyen n uẓeṭṭa ur nelli ara d ilelliyen
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: Asnas-agi ad yeḍfeṛ udiγ ad d-yazen armud-ik
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
