Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Tuqqniwt
Development:
  name: Taneflit
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Uraren
Graphics:
  name: Tiẓrudlifin
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Tadrimt
Multimedia:
  name: Umuγ n ugetmedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Asnirem
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Tiliγri d SMS
Reading:
  name: Taγuri
Science & Education:
  name: Tussna & Usegmi
Security:
  name: Taγellist
Sports & Health:
  name: Addal & Tazmert
System:
  name: Anagraw
Theming:
  name: Aggan
Time:
  name: Akud
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Tira
