Ads:
  description: हे अँप जाहिराती देखील
  icon: ic_antifeature_ads.xml
DisabledAlgorithm:
  description: या अँपची रक्षाप्रणाली स्वाक्षरी कुमकुवत आहे
  icon: ic_antifeature_disabledalgorithm.xml
KnownVuln:
  description: या अँँप्पमध्ये एक ज्ञात सुरक्षितता भेद आढळला आहे
  icon: ic_antifeature_knownvuln.xml
NSFW:
  icon: ic_antifeature_nsfw.xml
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: मूळ सांकेतिक शब्दसंग्रह आता उपलब्ध होणार नसल्याने, अद्ययावतन शक्य नाही.
NonFreeAdd:
  description: हे अँप काही सशुल्क अँप्सचे प्रोत्साहन देखील करते
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  description: या अँपमध्ये गैर मोफत सामग्री चा समावेश आहे
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  description: हे अँप इतर काही सशुल्क अँप्स वर अवलंबून आहे
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  description: हे अँप काही सशुल्क सुविधांचे प्रोत्साहन कर
  icon: ic_antifeature_nonfreenet.xml
Tracking:
  description: हे ऍप तुमच्या हालचालीवर पाळत ठेऊन नोंद करते
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  description: बाह्यस्त्रोतातुन वापरला गेलेला काही मुळ सांकेतिक शब्दसंग्रह पुर्णतः
    खुला नाही
  icon: ic_antifeature_upstreamnonfree.xml
