Ads:
  description: Diese App enthält Werbung
  name: Werbung
DisabledAlgorithm:
  description: Diese App hat eine schwache Sicherheitssignatur
  name: Mit einem unsicheren Algorithmus signiert
KnownVuln:
  description: Diese App enthält eine bekannte Sicherheitslücke
  name: Bekannte Sicherheitslücke
NSFW:
  description: Diese App enthält Inhalte, die nicht überall veröffentlicht oder sichtbar
    sein sollten
  name: NSFW
NoSourceSince:
  name: Der Quellcode ist nicht mehr erhältlich, keine Aktualisierungen möglich.
NonFreeAdd:
  description: Diese App bewirbt nicht-quelloffene Erweiterungen
  name: Nicht-quelloffene Erweiterungen
NonFreeAssets:
  description: Diese App enthält nicht-quelloffene Bestandteile
  name: Nicht-quelloffene Bestandteile
NonFreeDep:
  description: Diese App ist abhängig von anderen nicht-quelloffenen Apps
  name: Nicht-quelloffene Abhängigkeiten
NonFreeNet:
  description: Diese App bewirbt nicht-quelloffene Netzwerkdienste
  name: Nicht-quelloffene Netzwerkdienste
Tracking:
  description: Diese App verfolgt und versendet Ihre Aktivitäten
  name: Tracking
UpstreamNonFree:
  description: Der Originalcode ist nicht völlig quelloffen
  name: Originalcode nicht-quelloffen
