Connectivity:
  icon: Symbol Verbindung
  name: Verbindung
Development:
  icon: Symbol Entwicklung
  name: Entwicklung
Games:
  icon: Symbol Spiele
  name: Spiele
Graphics:
  icon: Symbol Grafik
  name: Grafik
Internet:
  icon: Symbol Internet
  name: Internet
Money:
  icon: Symbol Geld
  name: Geld
Multimedia:
  name: Multimedia
Navigation:
  icon: Symbol Navigation
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  icon: Symbol Lesen
  name: Lesen
Science & Education:
  icon: Symbol Wissenschaft & Bildung
  name: Wissenschaft & Bildung
Security:
  icon: Symbol Sicherheit
  name: Sicherheit
Sports & Health:
  name: Sport & Gesundheit
System:
  icon: Symbol System
  name: System
Theming:
  icon: Symbol Aussehen
  name: Aussehen
Time:
  name: Zeit
Writing:
  icon: Symbol Schreiben
  name: Schreiben
