Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Verbindung
Development:
  name: Entwicklung
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spiele
Graphics:
  name: Grafik
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Geld
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigation
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon / SMS
Reading:
  name: Lesen
Science & Education:
  name: Wissenschaft & Bildung
Security:
  name: Sicherheit
Sports & Health:
  name: Sport / Gesundheit
System:
  name: System
Theming:
  name: Aussehen
Time:
  name: Zeit
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Schreiben
