Connectivity:
  name: Verbindung
  icon: Symbol Verbindung
Development:
  name: Entwicklung
  icon: Symbol Entwicklung
Games:
  name: Spiele
  icon: Symbol Spiele
Graphics:
  name: Grafik
  icon: Symbol Grafik
Internet:
  name: Internet
  icon: Symbol Internet
Money:
  name: Geld
  icon: Symbol Geld
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
  icon: Symbol Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Lesen
  icon: Symbol Lesen
Science & Education:
  name: Wissenschaft & Bildung
  icon: Symbol Wissenschaft & Bildung
Security:
  name: Sicherheit
  icon: Symbol Sicherheit
Sports & Health:
  name: Sport & Gesundheit
System:
  name: System
  icon: Symbol System
Theming:
  name: Aussehen
  icon: Symbol Aussehen
Time:
  name: Zeit
Writing:
  name: Schreiben
  icon: Symbol Schreiben
