Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Tilkobling
Development:
  name: Utvikling
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Spill
Graphics:
  name: Grafikk
Internet:
  name: Internett
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Penger
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigasjon
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon og SMS
Reading:
  name: Lesing
Science & Education:
  name: Vitenskap & utdanning
Security:
  name: Sikkerhet
Sports & Health:
  name: Idrett og helse
System:
  name: System
Theming:
  name: Tilpasning
Time:
  name: Tid
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Skriving
