Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Conectividá
Development:
  name: Desendolcu
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Xuegos
Graphics:
  name: Graphics
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Dineru
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navegación
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefonía y SMS
Reading:
  name: Llectura
Science & Education:
  name: Ciencia y educación
Security:
  name: Seguranza
Sports & Health:
  name: Deporte y salú
System:
  name: Sistema
Theming:
  name: Aspeutu
Time:
  name: Time
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Escritura
