Ads:
  description: Questa app contiene pubblicità
  icon: ic_antifeature_ads.xml
  name: Annunci
DisabledAlgorithm:
  description: Questa applicazione ha una firma digitale debole
  icon: ic_antifeature_disabledalgorithm.xml
  name: Firmato usando un algoritmo non sicuro
KnownVuln:
  description: Questa applicazione contiene una falla di sicurezza nota
  icon: ic_antifeature_knownvuln.xml
  name: Vulnerabilità conosciuta
NSFW:
  description: Questa app ha contenuti che non dovrebbero essere pubblicizzati o visibili
    ovunque
  icon: ic_antifeature_nsfw.xml
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
  name: Il codice sorgente non è più disponibile, aggiornamenti non possibili.
NonFreeAdd:
  description: Questa app promuove add-on non liberi
  icon: ic_antifeature_nonfreeadd.xml
  name: Addon non liberi
NonFreeAssets:
  description: Questa app contiene risorse non libere
  icon: ic_antifeature_nonfreeassets.xml
  name: Risorse non libere
NonFreeDep:
  description: Questa app dipende da altre app non libere
  icon: ic_antifeature_nonfreedep.xml
  name: Dipendenze non libere
NonFreeNet:
  description: Questa app promuove servizi di rete non liberi
  icon: ic_antifeature_nonfreenet.xml
  name: Servizi di rete non liberi
Tracking:
  description: Questa app monitora e riferisce sulle tue attività
  icon: ic_antifeature_tracking.xml
  name: Tracciamento
UpstreamNonFree:
  description: Il codice sorgente a monte non è completamente libero
  icon: ic_antifeature_upstreamnonfree.xml
  name: Non libero a monte
