Connectivity:
  name: Connettività
  icon: category_connectivity.png
Development:
  name: Sviluppo
  icon: category_development.png
Games:
  name: Giochi
  icon: category_games.png
Graphics:
  name: Grafica
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Finanze
  icon: category_money.png
Multimedia:
  name: Multimedia
Navigation:
  name: Navigazione
  icon: category_navigation.png
Phone & SMS:
  name: Telefono e SMS
Reading:
  name: Lettura
  icon: category_reading.png
Science & Education:
  name: Scienza ed educazione
  icon: category_science_education.png
Security:
  name: Sicurezza
  icon: category_security.png
Sports & Health:
  name: Sport e salute
System:
  name: Sistema
  icon: category_system.png
Theming:
  name: Tematizzazione
  icon: category_theming.png
Time:
  name: Tempo
Writing:
  name: Scrittura
  icon: category_writing.png
