Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Connettività
Development:
  name: Sviluppo
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Giochi
Graphics:
  name: Grafica
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Finanze
Multimedia:
  name: Multimedia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigazione
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefono e SMS
Reading:
  name: Lettura
Science & Education:
  name: Scienza ed educazione
Security:
  name: Sicurezza
Sports & Health:
  name: Sport e salute
System:
  name: Sistema
Theming:
  name: Tematizzazione
Time:
  name: Tempo
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Scrittura
