Connectivity:
  name: Connettività
Development:
  name: Sviluppo
Games:
  name: Giochi
Graphics:
  name: Grafica
Internet:
  name: Internet
Money:
  name: Finanze
Multimedia:
  name: Multimedia
Navigation:
  name: Navigazione
Phone & SMS:
  name: Telefono e SMS
Reading:
  name: Lettura
Science & Education:
  name: Scienza ed educazione
Security:
  name: Sicurezza
Sports & Health:
  name: Sport e salute
System:
  name: Sistema
Theming:
  name: Personalizzazione
Time:
  name: Tempo
Writing:
  name: Scrittura
Bookmark:
  name: Segnalibri
Calculator:
  name: Calcolatrice
Ebook Reader:
  name: Lettore di Ebook
Email:
  name: Email
Gallery:
  name: Galleria
Icon Pack:
  name: Pacchetto di icone
Messaging:
  name: Messaggi
News:
  name: Notizie
Note:
  name: Appunti
Podcast:
  name: Podcast
Shopping List:
  name: Lista della spesa
Social Network:
  name: Social Network
Unit Convertor:
  name: Convertitore di unità
Weather:
  name: Meteo
