Connectivity:
  name: קישוריות
Development:
  name: פיתוח
Games:
  name: משחקים
Graphics:
  name: גרפיקה
Internet:
  name: אינטרנט
Money:
  name: כלכלה
Multimedia:
  name: מולטימדיה
Navigation:
  name: ניווט
Phone & SMS:
  name: טלפון ומסרונים
Reading:
  name: קריאה
Science & Education:
  name: מדע וחינוך
Security:
  name: אבטחה
Sports & Health:
  name: בריאות וספורט
System:
  name: מערכת
Theming:
  name: עיצוב
Time:
  name: זמן
Writing:
  name: כתיבה
App Store & Updater:
  name: App Store & Updater
Bookmark:
  name: סימנייה
Browser:
  name: דפדפן
Calculator:
  name: מחשבון
Calendar & Agenda:
  name: לוח שנה וסדר יום
Cloud Storage & File Sync:
  name: אחסון בענן וסינכרון קבצים
DNS & Hosts:
  name: DNS & Hosts
Draw:
  name: צייר
Ebook Reader:
  name: קורא Ebook
Email:
  name: דוא"ל
File Encryption & Vault:
  name: הצפנת קבצים וכספת
File Transfer:
  name: העברת קבצים
Finance Manager:
  name: מנהל כספים
Gallery:
  name: גלריה
Icon Pack:
  name: ערכת אייקונים
Keyboard & IME:
  name: מקלדת ו־IME
Launcher:
  name: משגר
Local Media Player:
  name: נגן מדיה מקומי
Messaging:
  name: הודעות
News:
  name: חדשות
Note:
  name: פתק
Online Media Player:
  name: נגן מדיה מקוון
Pass Wallet:
  name: ארנק Pass
Password & 2FA:
  name: סיסמה ואימות דו-שלבי 2FA
Podcast:
  name: הסכת
Public Transport Map & Timetable:
  name: מפת תחבורה ציבורית ולוחות זמנים
Translation & Dictionary:
  name: תרגום ומילון
Unit Convertor:
  name: ממיר יחידות מידה
