Ads:
  description: Tato aplikace obsahuje reklamu
  name: Reklamy
DisabledAlgorithm:
  description: Tato aplikace má slabý bezpečnostní podpis
  name: Podepsáno pomocí nebezpečného algoritmu
KnownVuln:
  description: Tato aplikace má známou zranitelnost v zabezpečení
  name: Známá zranitelnost
NSFW:
  description: Tato aplikace obsahuje obsah, který by neměl bý publikovaný či viditelný
    kdekoli
  name: NSFW
NoSourceSince:
  name: Zdrojový kód už není k dispozici, aktualizace nejsou možné.
NonFreeAdd:
  description: Tato aplikace propaguje nesvobodné doplňky
  name: Nesvobodné doplňky
NonFreeAssets:
  description: Tato aplikace obsahuje nesvobodné části
  name: Nesvobodná aktiva
NonFreeDep:
  description: Tato aplikace závisí na ostatních nesvobodných aplikacích
  name: Nesvobodné závislosti
NonFreeNet:
  description: Tato aplikace propaguje nesvobodné síťové služby
  name: Nesvobodné síťové služby
Tracking:
  description: Tato aplikace zaznamenává a hlásí vaše aktivity
  name: Sledování
UpstreamNonFree:
  description: Originální zdrojový kód je částečně nesvovodný
  name: Nesvobodný Upstream
