Connectivity:
  name: Připojení
  icon: category_connectivity.png
Development:
  name: Vývoj
  icon: category_development.png
Games:
  name: Hry
  icon: category_games.png
Graphics:
  name: Grafika
  icon: category_graphics.png
Internet:
  name: Internet
  icon: category_internet.png
Money:
  name: Peníze
  icon: category_money.png
Multimedia:
  name: Multimédia
Navigation:
  name: Navigace
Phone & SMS:
  name: Telefon a SMS
Reading:
  name: Čtení
  icon: category_reading.png
Science & Education:
  name: Věda a vzdělání
  icon: category_science_education.png
Security:
  name: Zabezpečení
  icon: category_security.png
Sports & Health:
  name: Sport a zdraví
System:
  name: Systém
  icon: category_system.png
Theming:
  name: Vzhledy
  icon: category_theming.png
Time:
  name: Čas
Writing:
  name: Psaní
  icon: category_writing.png
