Ads:
  icon: ic_antifeature_ads.xml
Connectivity:
  name: Připojení
Development:
  name: Vývoj
DisabledAlgorithm:
  icon: ic_antifeature_disabledalgorithm.xml
Games:
  name: Hry
Graphics:
  name: Grafika
Internet:
  name: Internet
KnownVuln:
  icon: ic_antifeature_knownvuln.xml
Money:
  name: Peníze
Multimedia:
  name: Multimédia
NSFW:
  icon: ic_antifeature_nsfw.xml
Navigation:
  name: Navigace
NoSourceSince:
  icon: ic_antifeature_nosourcesince.xml
NonFreeAdd:
  icon: ic_antifeature_nonfreeadd.xml
NonFreeAssets:
  icon: ic_antifeature_nonfreeassets.xml
NonFreeDep:
  icon: ic_antifeature_nonfreedep.xml
NonFreeNet:
  icon: ic_antifeature_nonfreenet.xml
Phone & SMS:
  name: Telefon a SMS
Reading:
  name: Čtení
Science & Education:
  name: Věda a vzdělání
Security:
  name: Zabezpečení
Sports & Health:
  name: Sport a zdraví
System:
  name: Systém
Theming:
  name: Vzhledy
Time:
  name: Čas
Tracking:
  icon: ic_antifeature_tracking.xml
UpstreamNonFree:
  icon: ic_antifeature_upstreamnonfree.xml
Writing:
  name: Psaní
