archive:
  name: Archiv F-Droid
  icon: fdroid-icon.png
  description: Archiv oficiálního repozitáře svobodného softwaru F-Droid. Aplikace zde jsou staré a mohou obsahovat známé chyby a bezpečnostní problémy!
repo:
  description: Oficiální repozitář svobodného softwaru F-Droid. Vše v tomto repozitáři je vždy sestaveno ze zdrojového kódu.
  name: F-Droid
  icon: fdroid-icon.png
